config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls")),
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

users/urls.py
from django.urls import path

from users.views.manager import (ManagerClientDetailView, ManagerClientsListView, ManagerDashboardView,
                                 ManagerMailingDetailView, ManagerMailingDisableView, ManagerMailingsListView,
                                 ManagerUserDetailView, ManagerUsersListView, manager_toggle_block)
from users.views.password_reset import (UserPasswordResetCompleteView, UserPasswordResetConfirmView,
                                        UserPasswordResetDoneView, UserPasswordResetView)
from users.views.user import (ConfirmEmailView, CustomLoginView, CustomLogoutView, CustomRegistrationView,
                              ProfileDeleteView, ProfileDetailView, ProfileUpdateView, RegistrationDoneView)

app_name = "users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("registration/", CustomRegistrationView.as_view(), name="registration"),
    path("registration/done/", RegistrationDoneView.as_view(), name="registration_done"),
    path("confirm_email/<uidb64>/<token>/", ConfirmEmailView.as_view(), name="confirm_email"),
    path("profile/", ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path("profile/delete/", ProfileDeleteView.as_view(), name="profile_delete"),
    path("manager/", ManagerDashboardView.as_view(), name="manager_dashboard"),
    path("manager/clients/", ManagerClientsListView.as_view(), name="manager_clients_list"),
    path("manager/client/<int:pk>/", ManagerClientDetailView.as_view(), name="manager_client_detail"),
    path("manager/users/", ManagerUsersListView.as_view(), name="manager_users_list"),
    path("manager/mailings/", ManagerMailingsListView.as_view(), name="manager_mailings_list"),
    path("manager/mailing/<int:pk>/", ManagerMailingDetailView.as_view(), name="manager_mailing_detail"),
    path("manager/mailing/<int:pk>/disable/", ManagerMailingDisableView.as_view(), name="manager_mailing_disable"),
    path("manager/user/<int:pk>/", ManagerUserDetailView.as_view(), name="manager_user_detail"),
    path("manager/user/<int:pk>/toggle_block/", manager_toggle_block, name="manager_toggle_block"),
    path("password_reset/", UserPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_reset/complete/", UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

users/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import CreateView, DeleteView, DetailView, TemplateView, UpdateView

from config import settings

from .forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from .models import User


class CustomLoginView(LoginView):
    template_name = "users/login.html"
    form_class = UserLoginForm


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy("mailing:index")


class CustomRegistrationView(CreateView):
    template_name = "users/registration.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("users:registration_done")

    def form_valid(self, form):
        response = super().form_valid(form)
        user = self.object
        self.send_confirmation_email(user)
        return response

    def send_confirmation_email(self, user):
        """
        Отправка письма со ссылкой для подтверждения email.
        """
        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)

        confirm_url = self.request.build_absolute_uri(
            reverse("users:confirm_email", kwargs={"uidb64": uidb64, "token": token})
        )

        subject = "Подтверждение регистрации"
        message = (
            "Спасибо за регистрацию в SkyMail!\n\n"
            f"Для завершения регистрации перейдите по ссылке:\n{confirm_url}\n\n"
            "Если вы не регистрировались на нашем сайте, просто проигнорируйте это письмо."
        )

        from_email = getattr(settings, "DEFAULT_FROM_EMAIL", os.getenv("FROM_EMAIL"))
        send_mail(subject, message, from_email, [user.email])


class RegistrationDoneView(TemplateView):
    template_name = "users/registration_done.html"


class ConfirmEmailView(TemplateView):
    template_name = "users/confirm_email.html"

    def get_success_url(self):
        return reverse("users:login") + "?email_confirmed=1"

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs.get("uidb64")
        token = kwargs.get("token")

        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect(self.get_success_url())
        else:
            return TemplateResponse(request, "users/confirm_email_invalid.html", {})


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/profile_detail.html"
    context_object_name = "user"

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile_form.html"
    success_url = reverse_lazy("users:profile_detail")

    def get_object(self, queryset=None):
        return self.request.user


class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = "users/profile_confirm_delete.html"
    success_url = reverse_lazy("mailing:index")

    def get_object(self, queryset=None):
        return self.request.user

users/views/manager.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView

from mailing.models import Client, Mailing, MailingLog
from users.mixins import ManagerRequiredMixin
from users.models import User


class ManagerDashboardView(ManagerRequiredMixin, TemplateView):
    """Главная панель управления менеджера с общей статистикой."""

    template_name = "users/manager/manager_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        users_qs = User.objects.filter(is_manager=False).exclude(is_staff=True, is_superuser=True)

        context["total_users"] = users_qs.count()
        context["blocked_users"] = users_qs.filter(is_active=False).count()
        context["active_users"] = users_qs.filter(is_active=True).count()

        mailings_qs = Mailing.objects.filter(owner__is_manager=False)
        context["total_mailings"] = mailings_qs.count()

        context["active_mailings"] = mailings_qs.filter(status="started").count()
        context["disabled_mailings"] = mailings_qs.exclude(status="started").count()

        return context


class ManagerClientsListView(PermissionRequiredMixin, ManagerRequiredMixin, ListView):
    """Список всех клиентов в системе для просмотра менеджером."""

    model = Client
    template_name = "users/manager/manager_clients_list.html"
    context_object_name = "clients"
    paginate_by = 10
    permission_required = "mailing.can_view_all_clients"

    def get_queryset(self):
        return Client.objects.select_related("owner").all()


class ManagerClientDetailView(PermissionRequiredMixin, ManagerRequiredMixin, DetailView):
    """Детальная информация о клиенте для менеджера."""

    model = Client
    template_name = "users/manager/manager_client_detail.html"
    context_object_name = "client"
    permission_required = "mailing.can_view_all_clients"


class ManagerUsersListView(PermissionRequiredMixin, ManagerRequiredMixin, ListView):
    """Список пользователей для управления доступом и блокировки."""

    model = User
    template_name = "users/manager/manager_users_list.html"
    context_object_name = "users"
    paginate_by = 10
    permission_required = "users.can_view_all_users"

    def get_queryset(self):
        return (
            User.objects.filter(is_manager=False)
            .exclude(is_staff=True, is_superuser=True)
            .annotate(
                clients_count=Count("clients", distinct=True),
                mailings_count=Count("mailings", distinct=True),
            )
        )


class ManagerUserDetailView(PermissionRequiredMixin, ManagerRequiredMixin, DetailView):
    """Детальная информация о пользователе с его клиентами и рассылками."""

    model = User
    template_name = "users/manager/manager_user_detail.html"
    context_object_name = "view_user"
    permission_required = "users.can_view_all_users", "users.can_block_users"

    def get_queryset(self):
        return (
            User.objects.filter(is_manager=False)
            .exclude(is_staff=True, is_superuser=True)
            .annotate(
                clients_count=Count("clients", distinct=True),
                mailings_count=Count("mailings", distinct=True),
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object

        context["last_clients"] = Client.objects.filter(owner=user).order_by("-id")[:5]
        context["last_mailings"] = Mailing.objects.filter(owner=user).order_by("-id")[:5]

        return context


def is_manager(user: User) -> bool:
    """Проверяет, является ли пользователь менеджером."""
    return user.is_authenticated and user.is_manager


@permission_required("users.can_block_users", raise_exception=True)
@user_passes_test(is_manager)
@login_required
def manager_toggle_block(request, pk):
    """Переключает статус блокировки пользователя."""
    user_obj = get_object_or_404(
        User.objects.filter(is_manager=False).exclude(is_staff=True, is_superuser=True),
        pk=pk,
    )
    user_obj.is_active = not user_obj.is_active
    user_obj.save()
    return redirect("users:manager_user_detail", pk=pk)


class ManagerMailingsListView(PermissionRequiredMixin, ManagerRequiredMixin, ListView):
    """Список всех рассылок в системе для мониторинга менеджером."""

    model = Mailing
    template_name = "users/manager/manager_mailings_list.html"
    context_object_name = "mailings"
    paginate_by = 10
    permission_required = "mailing.can_view_all_mailings"

    def get_queryset(self):
        return Mailing.objects.all().prefetch_related("clients").select_related("message")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings_qs = self.get_queryset()

        context["total_mailings"] = mailings_qs.count()
        context["started_mailings"] = mailings_qs.filter(status="started").count()
        context["finished_mailings"] = mailings_qs.filter(status="finished").count()

        return context


class ManagerMailingDetailView(PermissionRequiredMixin, ManagerRequiredMixin, DetailView):
    """Детальная информация о рассылке с логами отправки и статистикой."""

    model = Mailing
    template_name = "users/manager/manager_mailing_detail.html"
    context_object_name = "mailing"
    permission_required = ("mailing.can_view_all_mailings", "mailing.can_disable_mailings")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        # как и у обычного пользователя — динамически обновляем статус
        obj.update_status()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing = self.object
        now = timezone.now()

        # флаги интервала — если захочешь что-то подсвечивать менеджеру
        interval_invalid = mailing.start_time >= mailing.end_time
        before_window = mailing.start_time > now
        after_window = mailing.end_time < now

        logs_qs = MailingLog.objects.filter(mailing=mailing).select_related("client").order_by("-attempt_time")

        stats = logs_qs.aggregate(
            total=Count("id"),
            success=Count("id", filter=Q(status="success")),
            failed=Count("id", filter=Q(status="failed")),
        )

        context["logs"] = logs_qs
        context["stats"] = stats
        context["interval_invalid"] = interval_invalid
        context["before_window"] = before_window
        context["after_window"] = after_window
        context["now"] = now

        return context


class ManagerMailingDisableView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """Представление для принудительного отключения рассылки менеджером."""

    permission_required = "mailing.can_disable_mailings"

    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)

        mailing.end_time = timezone.now()
        mailing.save(update_fields=["end_time"])
        mailing.update_status()
        messages.success(request, "Рассылка была отключена менеджером.")

        return redirect("users:manager_mailing_detail", pk=mailing.pk)

users/views/password_reset.py
from django.contrib.auth.views import (PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import reverse_lazy

from users.forms import UserSetPasswordForm


class UserPasswordResetView(PasswordResetView):
    """Отображает и обрабатывает форму запроса сброса пароля."""

    template_name = "registration/password_reset_form.html"

    email_template_name = "registration/password_reset_email.txt"
    html_email_template_name = "registration/password_reset_email.html"
    subject_template_name = "registration/password_reset_subject.txt"
    success_url = reverse_lazy("users:password_reset_done")


class UserPasswordResetDoneView(PasswordResetDoneView):
    """Отображает страницу подтверждения отправки письма для сброса пароля."""

    template_name = "registration/password_reset_done.html"


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    """Обрабатывает форму установки нового пароля по ссылке из письма."""

    template_name = "registration/password_reset_confirm.html"
    form_class = UserSetPasswordForm
    success_url = reverse_lazy("users:password_reset_complete")


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    """Отображает страницу успешного сброса пароля."""

    template_name = "registration/password_reset_complete.html"

users/templates/users/manager/manager_client_detail.html
{# manager_client_detail.html #}
{% extends "mailing/base.html" %}
{% load static %}

{% block title %}Клиент сервиса — {{ client.email }}{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">Клиент сервиса</h1>
</div>

<div class="row g-4">
    <!-- Левая колонка: информация о клиенте -->
    <div class="col-md-8">
        <div class="card border-0 shadow-sm mb-4">
            <div class="card-body">
                <h5 class="card-title mb-3">Информация о клиенте</h5>

                <dl class="row mb-0">
                    <dt class="col-sm-3">Email</dt>
                    <dd class="col-sm-9">
                        <strong>{{ client.email }}</strong>
                    </dd>

                    <dt class="col-sm-3">ФИО</dt>
                    <dd class="col-sm-9">
                        {% if client.name %}
                            {{ client.name }}
                        {% else %}
                            <span class="text-muted">(не указано)</span>
                        {% endif %}
                    </dd>

                    <dt class="col-sm-3">Комментарий</dt>
                    <dd class="col-sm-9">
                        {% if client.comment %}
                            <p class="mb-0">{{ client.comment|linebreaksbr }}</p>
                        {% else %}
                            <span class="text-muted">(нет комментария)</span>
                        {% endif %}
                    </dd>

                    <dt class="col-sm-3 mt-3">Владелец</dt>
                    <dd class="col-sm-9 mt-3">
                        {% if client.owner %}
                            {% if not client.owner.is_manager %}
                                <a href="{% url 'users:manager_user_detail' client.owner.pk %}">
                                    {{ client.owner.email }}
                                </a>
                            {% else %}
                                <a href="{% url 'users:profile_detail' %}">
                                    {{ client.owner.email }}
                                </a>
                            {% endif %}
                        {% else %}
                            <span class="text-muted">—</span>
                        {% endif %}
                    </dd>
                </dl>
            </div>
        </div>
    </div>

    <!-- Правая колонка: действия -->
    <div class="col-md-4">
        <div class="card border-0 shadow-sm">
            <div class="card-body">
                <h5 class="card-title mb-3">Действия</h5>

                <div class="d-grid gap-2">
                    <a href="{% url 'users:manager_clients_list' %}"
                       class="btn btn-outline-secondary">
                        <i class="bi bi-people me-1"></i> К списку клиентов
                    </a>

                    <a href="{% url 'users:manager_dashboard' %}"
                       class="btn btn-primary">
                        <i class="bi bi-speedometer2 me-1"></i> Панель менеджера
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/manager/manager_clients_list.html
{% extends "mailing/base.html" %}
{% load static %}

{% block title %}Клиенты сервиса — SkyMail{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">Клиенты сервиса</h1>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                <tr>
                    <th>Email</th>
                    <th>ФИО</th>
                    <th>Комментарий</th>
                    <th class="text-end">Действия</th>
                </tr>
                </thead>
                <tbody>
                {% for client in clients %}
                <tr>
                    <td>{{ client.email }}</td>

                    <td>
                        {% if client.name %}
                            {{ client.name }}
                        {% else %}
                            <span class="text-muted">(не указано)</span>
                        {% endif %}
                    </td>

                    <td>{{ client.comment|default:"—" }}</td>

                    <td class="text-end">
                        <a href="{% url 'users:manager_client_detail' client.pk %}"
                           class="btn btn-sm btn-outline-secondary">
                            <i class="bi bi-three-dots"></i> Подробнее
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center py-3 text-muted">
                        Клиенты ещё не добавлены.
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'users:manager_dashboard' %}" class="btn btn-primary mt-3">
        Назад в панель менеджера
    </a>
</div>

{% if is_paginated %}
<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Назад</span>
        </li>
        {% endif %}

        {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active">
            <span class="page-link">{{ page_num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперёд</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Вперёд</span>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}
{% endblock %}

users/templates/users/manager/manager_dashboard.html
<!-- manager_dashboard.html -->
{% extends "mailing/base.html" %}

{% block title %}Панель менеджера — SkyMail{% endblock %}

{% block content %}
  <h1 class="text-center mb-4 text-primary">Панель менеджера сервиса</h1>

  {# --- Блок общей статистики по пользователям --- #}
  <div class="row g-4 justify-content-center mb-4">
    <div class="col-md-4">
      <div class="card border-0 text-center p-4">
        <div class="card-body">
          <h5 class="card-title text-muted">Пользователей сервиса</h5>
          <h2 class="display-5 fw-bold text-primary">{{ total_users }}</h2>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card border-0 text-center p-4">
        <div class="card-body">
          <h5 class="card-title text-muted">Заблокированные пользователи</h5>
          <h2 class="display-5 fw-bold text-danger">{{ blocked_users }}</h2>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card border-0 text-center p-4">
        <div class="card-body">
          <h5 class="card-title text-muted">Активные пользователи</h5>
          <h2 class="display-5 fw-bold text-success">{{ active_users }}</h2>
        </div>
      </div>
    </div>
  </div>

  {# --- Блок статистики по рассылкам --- #}
  <div class="row g-4 justify-content-center mb-4">
    <div class="col-md-4">
      <div class="card border-0 text-center p-4">
        <div class="card-body">
          <h5 class="card-title text-muted">Всего рассылок</h5>
          <h2 class="display-5 fw-bold text-primary">{{ total_mailings }}</h2>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card border-0 text-center p-4">
        <div class="card-body">
          <h5 class="card-title text-muted">Активные рассылки</h5>
          <h2 class="display-5 fw-bold text-success">{{ active_mailings }}</h2>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card border-0 text-center p-4">
        <div class="card-body">
          <h5 class="card-title text-muted">Отключённые рассылки</h5>
          <h2 class="display-5 fw-bold text-warning">{{ disabled_mailings }}</h2>
        </div>
      </div>
    </div>
  </div>

  {# --- Блок быстрых действий менеджера --- #}
  <div class="row g-4 justify-content-center">
    <div class="col-md-4">
      <div class="card border-0 h-100">
        <div class="card-body d-flex flex-column justify-content-between">
          <div>
            <h5 class="card-title text-primary">Пользователи</h5>
            <p class="card-text text-muted">
              Просмотр списка всех пользователей сервиса и управление блокировками.
            </p>
          </div>
          <a href="{% url 'users:manager_users_list' %}" class="btn btn-outline-primary mt-2">
            Открыть список пользователей
          </a>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card border-0 h-100">
        <div class="card-body d-flex flex-column justify-content-between">
          <div>
            <h5 class="card-title text-primary">Все рассылки</h5>
            <p class="card-text text-muted">
              Обзор всех рассылок сервиса и отключение подозрительной активности.
            </p>
          </div>
          <a href="{% url 'users:manager_mailings_list' %}" class="btn btn-outline-primary mt-2">
            Открыть все рассылки
          </a>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card border-0 h-100">
        <div class="card-body d-flex flex-column justify-content-between">
          <div>
            <h5 class="card-title text-primary">Клиенты</h5>
            <p class="card-text text-muted">
              Просмотр всех клиентов сервиса.
            </p>
          </div>
          <a href="{% url 'users:manager_clients_list' %}" class="btn btn-outline-primary mt-2">
            Открыть всех клиентов
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/manager/manager_mailing_detail.html
{% extends "mailing/base.html" %}
{% load static %}

{% block title %}Рассылка — {{ mailing.message.subject|default:"(без темы)" }}{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">Рассылка</h1>
</div>

<div class="row g-4">

    <!-- Левая колонка: общая информация и логи -->
    <div class="col-md-8">
        {# interval_invalid можешь тоже передать из менеджерской вьюхи, если нужно предупреждение #}
        {% include "mailing/includes/_mailing_detail_panel.html" with mailing=mailing logs=logs stats=stats %}
    </div>

    <!-- Правая колонка: действия менеджера -->
    <div class="col-md-4">
        <div class="card border-0 shadow-sm">
            <div class="card-body">

                <h5 class="card-title mb-3">Действия менеджера</h5>

                <div class="d-grid gap-2">

                    {% if perms.mailing.can_disable_mailings %}
                        {% if mailing.status == "started" %}
                        <form method="post" action="{% url 'users:manager_mailing_disable' mailing.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger w-100">
                                <i class="bi bi-stop-fill me-1"></i> Отключить рассылку
                            </button>
                        </form>
                        {% else %}
                        <p class="text-muted small mb-2">
                            Отключение доступно только для активных рассылок
                            (статус «Запущена»).
                        </p>
                        {% endif %}
                    {% endif %}

                    <a href="{% url 'users:manager_mailings_list' %}"
                       class="btn btn-outline-secondary">
                        <i class="bi bi-arrow-left me-1"></i> Назад к списку рассылок
                    </a>

                    <a href="{% url 'users:manager_dashboard' %}"
                       class="btn btn-primary">
                        <i class="bi bi-speedometer2 me-1"></i> Панель менеджера
                    </a>

                </div>

            </div>
        </div>
    </div>

</div>
{% endblock %}