config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls")),
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

mailing/urls.py
from django.urls import path

from mailing.views.clients import (ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView,
                                   ClientUpdateView)
from mailing.views.mailing_logs import MailingLogListView
from mailing.views.mailings import (MailingCreateView, MailingDeleteView, MailingDetailView, MailingListView,
                                    MailingRunView, MailingUpdateView)
from mailing.views.main import MailingTemplateView
from mailing.views.messages import (MessageCreateView, MessageDeleteView, MessageDetailView, MessageListView,
                                    MessageUpdateView)

app_name = "mailing"

urlpatterns = [
    path("", MailingTemplateView.as_view(), name="index"),
    path("client/", ClientListView.as_view(), name="client_list"),
    path("client/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("client/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("client/create/", ClientCreateView.as_view(), name="client_create"),
    path("message/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/run/", MailingRunView.as_view(), name="mailing_run"),
    path("mailing/log/", MailingLogListView.as_view(), name="mailing_log"),
]

users/urls.py
from django.urls import path

from users.views.manager import (ManagerClientDetailView, ManagerClientsListView, ManagerDashboardView,
                                 ManagerMailingDetailView, ManagerMailingDisableView, ManagerMailingsListView,
                                 ManagerUserDetailView, ManagerUsersListView, manager_toggle_block)
from users.views.password_reset import (UserPasswordResetCompleteView, UserPasswordResetConfirmView,
                                        UserPasswordResetDoneView, UserPasswordResetView)
from users.views.user import (ConfirmEmailView, CustomLoginView, CustomLogoutView, CustomRegistrationView,
                              ProfileDeleteView, ProfileDetailView, ProfileUpdateView, RegistrationDoneView)

app_name = "users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("registration/", CustomRegistrationView.as_view(), name="registration"),
    path("registration/done/", RegistrationDoneView.as_view(), name="registration_done"),
    path("confirm_email/<uidb64>/<token>/", ConfirmEmailView.as_view(), name="confirm_email"),
    path("profile/", ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path("profile/delete/", ProfileDeleteView.as_view(), name="profile_delete"),
    path("manager/", ManagerDashboardView.as_view(), name="manager_dashboard"),
    path("manager/clients/", ManagerClientsListView.as_view(), name="manager_clients_list"),
    path("manager/client/<int:pk>/", ManagerClientDetailView.as_view(), name="manager_client_detail"),
    path("manager/users/", ManagerUsersListView.as_view(), name="manager_users_list"),
    path("manager/mailings/", ManagerMailingsListView.as_view(), name="manager_mailings_list"),
    path("manager/mailing/<int:pk>/", ManagerMailingDetailView.as_view(), name="manager_mailing_detail"),
    path("manager/mailing/<int:pk>/disable/", ManagerMailingDisableView.as_view(), name="manager_mailing_disable"),
    path("manager/user/<int:pk>/", ManagerUserDetailView.as_view(), name="manager_user_detail"),
    path("manager/user/<int:pk>/toggle_block/", manager_toggle_block, name="manager_toggle_block"),
    path("password_reset/", UserPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_reset/complete/", UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

users/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import CreateView, DeleteView, DetailView, TemplateView, UpdateView

from config import settings

from .forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from .models import User


class CustomLoginView(LoginView):
    template_name = "users/login.html"
    form_class = UserLoginForm


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy("mailing:index")


class CustomRegistrationView(CreateView):
    template_name = "users/registration.html"
    form_class = UserRegistrationForm
    success_url = reverse_lazy("users:registration_done")

    def form_valid(self, form):
        response = super().form_valid(form)
        user = self.object
        self.send_confirmation_email(user)
        return response

    def send_confirmation_email(self, user):
        """
        Отправка письма со ссылкой для подтверждения email.
        """
        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)

        confirm_url = self.request.build_absolute_uri(
            reverse("users:confirm_email", kwargs={"uidb64": uidb64, "token": token})
        )

        subject = "Подтверждение регистрации"
        message = (
            "Спасибо за регистрацию в SkyMail!\n\n"
            f"Для завершения регистрации перейдите по ссылке:\n{confirm_url}\n\n"
            "Если вы не регистрировались на нашем сайте, просто проигнорируйте это письмо."
        )

        from_email = getattr(settings, "DEFAULT_FROM_EMAIL", os.getenv("FROM_EMAIL"))
        send_mail(subject, message, from_email, [user.email])


class RegistrationDoneView(TemplateView):
    template_name = "users/registration_done.html"


class ConfirmEmailView(TemplateView):
    template_name = "users/confirm_email.html"

    def get_success_url(self):
        return reverse("users:login") + "?email_confirmed=1"

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs.get("uidb64")
        token = kwargs.get("token")

        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect(self.get_success_url())
        else:
            return TemplateResponse(request, "users/confirm_email_invalid.html", {})


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/profile_detail.html"
    context_object_name = "user"

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile_form.html"
    success_url = reverse_lazy("users:profile_detail")

    def get_object(self, queryset=None):
        return self.request.user


class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = "users/profile_confirm_delete.html"
    success_url = reverse_lazy("mailing:index")

    def get_object(self, queryset=None):
        return self.request.user

users/views/manager.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView

from mailing.models import Client, Mailing, MailingLog
from users.mixins import ManagerRequiredMixin
from users.models import User


class ManagerDashboardView(ManagerRequiredMixin, TemplateView):
    """Главная панель управления менеджера с общей статистикой."""

    template_name = "users/manager/manager_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        users_qs = User.objects.filter(is_manager=False).exclude(is_staff=True, is_superuser=True)

        context["total_users"] = users_qs.count()
        context["blocked_users"] = users_qs.filter(is_active=False).count()
        context["active_users"] = users_qs.filter(is_active=True).count()

        mailings_qs = Mailing.objects.filter(owner__is_manager=False)
        context["total_mailings"] = mailings_qs.count()

        context["active_mailings"] = mailings_qs.filter(status="started").count()
        context["disabled_mailings"] = mailings_qs.exclude(status="started").count()

        return context


class ManagerClientsListView(PermissionRequiredMixin, ManagerRequiredMixin, ListView):
    """Список всех клиентов в системе для просмотра менеджером."""

    model = Client
    template_name = "users/manager/manager_clients_list.html"
    context_object_name = "clients"
    paginate_by = 10
    permission_required = "mailing.can_view_all_clients"

    def get_queryset(self):
        return Client.objects.select_related("owner").all()


class ManagerClientDetailView(PermissionRequiredMixin, ManagerRequiredMixin, DetailView):
    """Детальная информация о клиенте для менеджера."""

    model = Client
    template_name = "users/manager/manager_client_detail.html"
    context_object_name = "client"
    permission_required = "mailing.can_view_all_clients"


class ManagerUsersListView(PermissionRequiredMixin, ManagerRequiredMixin, ListView):
    """Список пользователей для управления доступом и блокировки."""

    model = User
    template_name = "users/manager/manager_users_list.html"
    context_object_name = "users"
    paginate_by = 10
    permission_required = "users.can_view_all_users"

    def get_queryset(self):
        return (
            User.objects.filter(is_manager=False)
            .exclude(is_staff=True, is_superuser=True)
            .annotate(
                clients_count=Count("clients", distinct=True),
                mailings_count=Count("mailings", distinct=True),
            )
        )


class ManagerUserDetailView(PermissionRequiredMixin, ManagerRequiredMixin, DetailView):
    """Детальная информация о пользователе с его клиентами и рассылками."""

    model = User
    template_name = "users/manager/manager_user_detail.html"
    context_object_name = "view_user"
    permission_required = "users.can_view_all_users", "users.can_block_users"

    def get_queryset(self):
        return (
            User.objects.filter(is_manager=False)
            .exclude(is_staff=True, is_superuser=True)
            .annotate(
                clients_count=Count("clients", distinct=True),
                mailings_count=Count("mailings", distinct=True),
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object

        context["last_clients"] = Client.objects.filter(owner=user).order_by("-id")[:5]
        context["last_mailings"] = Mailing.objects.filter(owner=user).order_by("-id")[:5]

        return context


def is_manager(user: User) -> bool:
    """Проверяет, является ли пользователь менеджером."""
    return user.is_authenticated and user.is_manager


@permission_required("users.can_block_users", raise_exception=True)
@user_passes_test(is_manager)
@login_required
def manager_toggle_block(request, pk):
    """Переключает статус блокировки пользователя."""
    user_obj = get_object_or_404(
        User.objects.filter(is_manager=False).exclude(is_staff=True, is_superuser=True),
        pk=pk,
    )
    user_obj.is_active = not user_obj.is_active
    user_obj.save()
    return redirect("users:manager_user_detail", pk=pk)


class ManagerMailingsListView(PermissionRequiredMixin, ManagerRequiredMixin, ListView):
    """Список всех рассылок в системе для мониторинга менеджером."""

    model = Mailing
    template_name = "users/manager/manager_mailings_list.html"
    context_object_name = "mailings"
    paginate_by = 10
    permission_required = "mailing.can_view_all_mailings"

    def get_queryset(self):
        return Mailing.objects.all().prefetch_related("clients").select_related("message")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings_qs = self.get_queryset()

        context["total_mailings"] = mailings_qs.count()
        context["started_mailings"] = mailings_qs.filter(status="started").count()
        context["finished_mailings"] = mailings_qs.filter(status="finished").count()

        return context


class ManagerMailingDetailView(PermissionRequiredMixin, ManagerRequiredMixin, DetailView):
    """Детальная информация о рассылке с логами отправки и статистикой."""

    model = Mailing
    template_name = "users/manager/manager_mailing_detail.html"
    context_object_name = "mailing"
    permission_required = ("mailing.can_view_all_mailings", "mailing.can_disable_mailings")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        # как и у обычного пользователя — динамически обновляем статус
        obj.update_status()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing = self.object
        now = timezone.now()

        # флаги интервала — если захочешь что-то подсвечивать менеджеру
        interval_invalid = mailing.start_time >= mailing.end_time
        before_window = mailing.start_time > now
        after_window = mailing.end_time < now

        logs_qs = MailingLog.objects.filter(mailing=mailing).select_related("client").order_by("-attempt_time")

        stats = logs_qs.aggregate(
            total=Count("id"),
            success=Count("id", filter=Q(status="success")),
            failed=Count("id", filter=Q(status="failed")),
        )

        context["logs"] = logs_qs
        context["stats"] = stats
        context["interval_invalid"] = interval_invalid
        context["before_window"] = before_window
        context["after_window"] = after_window
        context["now"] = now

        return context


class ManagerMailingDisableView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """Представление для принудительного отключения рассылки менеджером."""

    permission_required = "mailing.can_disable_mailings"

    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)

        mailing.end_time = timezone.now()
        mailing.save(update_fields=["end_time"])
        mailing.update_status()
        messages.success(request, "Рассылка была отключена менеджером.")

        return redirect("users:manager_mailing_detail", pk=mailing.pk)

users/templates/users/_profile_card.html
<!-- _profile_card.html -->
{% load my_tags %}

<div class="col-lg-3 col-md-4 col-sm-6 mb-4">
    <div class="card h-100 shadow-sm border-0 product-card">
        <div class="product-img-wrapper">
            <img src="{{ user.avatar|media_filter }}" class="card-img-top" alt="{{ user.username }}">
        </div>

        <div class="card-body text-start p-2">
            <h6 class="card-title fw-semibold mb-1">{{ user.email }}</h6>

            {% if user.phone %}
            <p class="card-text small mb-2">Телефон: {{ user.phone }}</p>
            {% endif %}
        </div>
    </div>
</div>

users/templates/users/confirm_email.html
<!--confirm_email.html-->
{% extends "mailing/base.html" %}

{% block title %}Email подтверждён{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-3">Email успешно подтверждён!</h2>

    <p>
        Ваш аккаунт активирован. Теперь вы можете войти в систему
        и пользоваться сервисом рассылок.
    </p>

    <a href="{% url 'users:login' %}" class="btn btn-primary mt-3">Войти</a>
</div>
{% endblock %}

users/templates/users/confirm_email_invalid.html
<!--confirm_email_invalid.html-->
{% extends "mailing/base.html" %}
{% block title %}Ошибка подтверждения{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-danger">
        <h4 class="alert-heading">Не удалось подтвердить email</h4>
        <p>Ссылка для подтверждения недействительна или устарела. Попробуйте зарегистрироваться снова.</p>
    </div>
    <a href="{% url 'users:registration' %}" class="btn btn-primary">Зарегистрироваться</a>
    <a href="{% url 'mailing:index' %}" class="btn btn-secondary ms-2">На главную</a>
</div>
{% endblock %}

users/templates/users/login.html
<!--login.html-->
{% extends 'mailing/base.html' %}
{% block title %}Вход в SkyMailing{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="mb-4">Вход</h2>
    {% if request.GET.email_confirmed %}
    <div class="alert alert-success">
        Ваш email успешно подтвержден! Теперь вы можете войти в систему.
    </div>
    {% endif %}

    <form method="post" class="border rounded p-4 shadow-sm bg-white">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary w-100 mb-3">Войти</button>
        <a href="{% url 'users:password_reset' %}"
           class="btn btn-outline-secondary w-100">
            Забыли пароль?
        </a>
        <a href="{% url 'users:registration' %}"
           class="btn btn-outline-secondary w-100">
            Зарегистрироваться
        </a>
    </form>
</div>
{% endblock %}

users/templates/users/profile_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block title %}Удаление профиля — SkyMail{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="alert alert-warning">
        <h4 class="alert-heading">Удалить аккаунт?</h4>
        <p>Это действие необратимо. Все данные профиля будут удалены.</p>
    </div>

    <form method="post" class="d-flex gap-2">
        {% csrf_token %}
        <a href="{% url 'users:profile_detail' %}" class="btn btn-secondary">Отмена</a>
        <button type="submit" class="btn btn-danger">Удалить профиль</button>
    </form>
</div>
{% endblock %}

users/templates/users/profile_detail.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block title %}Профиль — SkyMailing{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-5 col-md-6 col-sm-8">
            <div class="card shadow-sm border-0 p-4">

                <div class="text-center">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}"
                             alt="avatar"
                             class="rounded-circle mb-3"
                             style="width: 150px; height: 150px; object-fit: cover;">
                    {% else %}
                        <img src="{% static 'img/default_avatar.png' %}"
                             alt="avatar"
                             class="rounded-circle mb-3"
                             style="width: 150px; height: 150px; object-fit: cover;">
                    {% endif %}
                </div>

                <h3 class="text-center mb-3">{{ user.email }}</h3>

                <ul class="list-group list-group-flush mb-4">
                    <li class="list-group-item">
                        <strong>Телефон:</strong>
                        {% if user.phone %} {{ user.phone }} {% else %} не указан {% endif %}
                    </li>
                </ul>

                <div class="d-flex justify-content-between">
                    <a href="{% url 'mailing:index' %}" class="btn btn-secondary">Назад</a>
                    <a href="{% url 'users:profile_edit'%}" class="btn btn-warning">Редактировать профиль</a>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile_form.html
<!-- profile_form.html -->
{% extends 'mailing/base.html' %}
{% block title %}Редактирование профиля — SkyMailing{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">

    <h2 class="mb-4">Редактирование профиля</h2>

    <form method="post" enctype="multipart/form-data" class="border rounded p-4 shadow-sm bg-white">
        {% csrf_token %}

        {% if form.errors %}
            <div class="alert alert-danger">
                <strong>Исправьте ошибки ниже:</strong>
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <div class="mb-3">
            {{ form.as_p }}
        </div>

        <!-- Текущее фото аватара -->
        {% if user.avatar %}
            <div class="mb-3">
                <label class="form-label fw-bold">Текущий аватар:</label><br>
                <img src="{{ user.avatar.url }}"
                     alt="avatar"
                     class="img-thumbnail mt-2"
                     style="max-width: 200px;">
            </div>

            <!-- Чекбокс удаления текущего аватара -->
            {% if 'delete_avatar' in form %}
                <div class="form-check mb-4">
                    {{ form.delete_avatar }}
                    <label for="{{ form.delete_avatar.id_for_label }}" class="form-check-label">
                        {{ form.delete_avatar.help_text }}
                    </label>
                </div>
            {% endif %}
        {% endif %}

        <!-- Превью нового изображения -->
        <div class="mb-3" id="previewBlock" style="display: none;">
            <label class="form-label fw-bold">Предпросмотр нового аватара:</label><br>
            <img id="preview" class="img-thumbnail mt-2" style="max-width: 200px;">
            <button type="button" id="clearSelected" class="btn btn-sm btn-outline-danger mt-2">
                Убрать выбранный файл
            </button>
        </div>

        <button type="submit" class="btn btn-primary mt-3 w-100">
            Сохранить изменения
        </button>

        <button type="button" class="btn btn-secondary mt-3 w-100"
                onclick="window.location.href='{% url 'users:profile_detail' %}'">
            Назад
        </button>
    </form>
</div>

<script>
document.addEventListener("DOMContentLoaded", () => {
    const fileInput = document.querySelector('input[type="file"][name="avatar"]');
    const previewBlock = document.getElementById("previewBlock");
    const preview = document.getElementById("preview");
    const clearBtn = document.getElementById("clearSelected");
    const clearCheckbox = document.getElementById("clear_avatar");

    if (fileInput) {
        fileInput.addEventListener("change", event => {
            const file = event.target.files[0];

            if (!file) {
                previewBlock.style.display = "none";
                return;
            }

            if (clearCheckbox) {
                clearCheckbox.checked = false;
            }

            const reader = new FileReader();
            reader.onload = e => {
                preview.src = e.target.result;
                previewBlock.style.display = "block";
            };
            reader.readAsDataURL(file);
        });
    }

    if (clearBtn) {
        clearBtn.addEventListener("click", () => {
            fileInput.value = "";
            previewBlock.style.display = "none";
        });
    }
});
</script>
{% endblock %}

users/templates/users/registration.html
{% extends 'mailing/base.html' %}

{% block title %}Регистрация в SkyMailing{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="mb-4">Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
{% endblock %}

users/templates/users/registration_done.html
<!--registration_done.html-->
{% extends "mailing/base.html" %}

{% block title %}Подтверждение email{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-3">Почти готово!</h2>

    <p>
        Мы отправили письмо с подтверждением на ваш email.<br>
        Пожалуйста, перейдите по ссылке в письме, чтобы активировать аккаунт
        и получить доступ к сервису рассылок.
    </p>

    <p class="text-muted">Если письмо не приходит — проверьте папку «Спам».</p>
</div>
{% endblock %}