config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls")),
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

mailing/urls.py
from django.urls import path

from mailing.views.clients import (ClientCreateView, ClientDeleteView, ClientDetailView, ClientListView,
                                   ClientUpdateView)
from mailing.views.mailing_logs import MailingLogListView
from mailing.views.mailings import (MailingCreateView, MailingDeleteView, MailingDetailView, MailingListView,
                                    MailingRunView, MailingUpdateView)
from mailing.views.main import MailingTemplateView
from mailing.views.messages import (MessageCreateView, MessageDeleteView, MessageDetailView, MessageListView,
                                    MessageUpdateView)

app_name = "mailing"

urlpatterns = [
    path("", MailingTemplateView.as_view(), name="index"),
    path("client/", ClientListView.as_view(), name="client_list"),
    path("client/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("client/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),
    path("client/create/", ClientCreateView.as_view(), name="client_create"),
    path("message/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>/", MessageDetailView.as_view(), name="message_detail"),
    path("message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete"),
    path("message/create/", MessageCreateView.as_view(), name="message_create"),
    path("mailing/", MailingListView.as_view(), name="mailing_list"),
    path("mailing/<int:pk>/", MailingDetailView.as_view(), name="mailing_detail"),
    path("mailing/<int:pk>/update/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailing/<int:pk>/delete/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("mailing/create/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailing/<int:pk>/run/", MailingRunView.as_view(), name="mailing_run"),
    path("mailing/log/", MailingLogListView.as_view(), name="mailing_log"),
]

users/urls.py
from django.urls import path

from users.views.manager import (ManagerClientDetailView, ManagerClientsListView, ManagerDashboardView,
                                 ManagerMailingDetailView, ManagerMailingDisableView, ManagerMailingsListView,
                                 ManagerUserDetailView, ManagerUsersListView, manager_toggle_block)
from users.views.password_reset import (UserPasswordResetCompleteView, UserPasswordResetConfirmView,
                                        UserPasswordResetDoneView, UserPasswordResetView)
from users.views.user import (ConfirmEmailView, CustomLoginView, CustomLogoutView, CustomRegistrationView,
                              ProfileDeleteView, ProfileDetailView, ProfileUpdateView, RegistrationDoneView)

app_name = "users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("registration/", CustomRegistrationView.as_view(), name="registration"),
    path("registration/done/", RegistrationDoneView.as_view(), name="registration_done"),
    path("confirm_email/<uidb64>/<token>/", ConfirmEmailView.as_view(), name="confirm_email"),
    path("profile/", ProfileDetailView.as_view(), name="profile_detail"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path("profile/delete/", ProfileDeleteView.as_view(), name="profile_delete"),
    path("manager/", ManagerDashboardView.as_view(), name="manager_dashboard"),
    path("manager/clients/", ManagerClientsListView.as_view(), name="manager_clients_list"),
    path("manager/client/<int:pk>/", ManagerClientDetailView.as_view(), name="manager_client_detail"),
    path("manager/users/", ManagerUsersListView.as_view(), name="manager_users_list"),
    path("manager/mailings/", ManagerMailingsListView.as_view(), name="manager_mailings_list"),
    path("manager/mailing/<int:pk>/", ManagerMailingDetailView.as_view(), name="manager_mailing_detail"),
    path("manager/mailing/<int:pk>/disable/", ManagerMailingDisableView.as_view(), name="manager_mailing_disable"),
    path("manager/user/<int:pk>/", ManagerUserDetailView.as_view(), name="manager_user_detail"),
    path("manager/user/<int:pk>/toggle_block/", manager_toggle_block, name="manager_toggle_block"),
    path("password_reset/", UserPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", UserPasswordResetDoneView.as_view(), name="password_reset_done"),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_reset/complete/", UserPasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

mailing/views/clients.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from mailing.forms import ClientForm
from mailing.mixins import OwnerAccessMixin, OwnerQuerysetMixin
from mailing.models import Client


class ClientListView(LoginRequiredMixin, OwnerQuerysetMixin, ListView):
    model = Client
    template_name = "mailing/client_list.html"
    context_object_name = "clients"
    paginate_by = 6


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = "mailing/client_form.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("mailing:client_list")


class ClientUpdateView(LoginRequiredMixin, OwnerAccessMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = "mailing/client_form.html"

    def get_success_url(self):
        return reverse_lazy("mailing:client_detail", kwargs={"pk": self.object.pk})


class ClientDetailView(LoginRequiredMixin, OwnerAccessMixin, DetailView):
    model = Client
    template_name = "mailing/client_detail.html"
    context_object_name = "client"


class ClientDeleteView(LoginRequiredMixin, OwnerAccessMixin, DeleteView):
    model = Client
    template_name = "mailing/client_confirm_delete.html"
    success_url = reverse_lazy("mailing:client_list")

mailing/views/mailing_logs.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.db.models import Count, Max, Q
from django.views.generic import ListView

from mailing.models import Mailing, MailingLog


class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog
    template_name = "mailing/mailing_logs.html"
    context_object_name = "mailing_log"
    paginate_by = 6

    cache_timeout = 120

    def get_queryset(self):
        """
        Ограничиваем логи:
        - обычный пользователь видит только свои рассылки;
        - менеджер с правом can_view_all_mailings видит всё.
        """
        qs = super().get_queryset().select_related("mailing", "mailing__message", "mailing__owner", "client")

        user = self.request.user

        if user.has_perm("mailing.can_view_all_mailings"):
            return qs

        return qs.filter(mailing__owner=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = getattr(self, "object_list", None) or self.get_queryset()
        user = self.request.user
        cache_prefix = self._get_cache_prefix(user)

        counters = cache.get(f"{cache_prefix}:counters")

        if counters is None:
            total_attempts = qs.count()
            success_count = qs.filter(status="success").count()
            failed_count = qs.filter(status="failed").count()

            if total_attempts:
                success_rate = round(success_count / total_attempts * 100)
                failed_rate = 100 - success_rate
            else:
                success_rate = 0
                failed_rate = 0

            if user.has_perm("mailing.can_view_all_mailings"):
                total_mailings = Mailing.objects.count()
            else:
                total_mailings = Mailing.objects.filter(owner=user).count()

            counters = {
                "total_mailings": total_mailings,
                "total_messages": success_count,
                "successful_attempts": success_count,
                "failed_attempts": failed_count,
                "success_rate": success_rate,
                "failed_rate": failed_rate,
            }

            cache.set(f"{cache_prefix}:counters", counters, self.cache_timeout)

        mailings_stats = cache.get(f"{cache_prefix}:mailings_stats")

        if mailings_stats is None:
            mailings_stats_qs = (
                Mailing.objects.filter(mailinglog__in=qs)
                .distinct()
                .annotate(
                    total_attempts=Count("mailinglog"),
                    success_count=Count(
                        "mailinglog",
                        filter=Q(mailinglog__status="success"),
                    ),
                    failed_count=Count(
                        "mailinglog",
                        filter=Q(mailinglog__status="failed"),
                    ),
                    last_attempt_time=Max("mailinglog__attempt_time"),
                )
                .select_related("message")
            )

            mailings_stats = list(mailings_stats_qs)

            for mailing in mailings_stats:
                if mailing.total_attempts:
                    mailing.success_rate = round(mailing.success_count / mailing.total_attempts * 100)
                else:
                    mailing.success_rate = 0

            cache.set(f"{cache_prefix}:mailings_stats", mailings_stats, self.cache_timeout)

        last_attempts = cache.get(f"{cache_prefix}:last_attempts")

        if last_attempts is None:
            last_attempts = list(qs.order_by("-attempt_time")[:10])
            cache.set(f"{cache_prefix}:last_attempts", last_attempts, self.cache_timeout)

        context.update(
            {
                **counters,
                "mailings_stats": mailings_stats,
                "last_attempts": last_attempts,
            }
        )

        return context

    @staticmethod
    def _get_cache_prefix(user) -> str:
        if user.has_perm("mailing.can_view_all_mailings"):
            return "mailinglogs:all"

        return f"mailinglogs:user:{user.pk}"

mailing/views/mailings.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from mailing.forms import MailingForm
from mailing.mixins import OwnerAccessMixin, OwnerQuerysetMixin
from mailing.models import Mailing, MailingLog
from mailing.services import run_mailing

logger = logging.getLogger("mailing")


class MailingListView(LoginRequiredMixin, OwnerQuerysetMixin, ListView):
    model = Mailing
    template_name = "mailing/mailing_list.html"
    context_object_name = "mailings"
    paginate_by = 6

    cache_timeout = 60

    def get_queryset(self):
        """
        Возвращаем рассылки текущего пользователя (или все для менеджера)
        и обновляем статус КАЖДОГО объекта только в памяти (save=False),
        чтобы не делать лишние UPDATE-запросы к БД при открытии списка.

        Фактическое сохранение статуса в БД происходит:
        - в детальном представлении (MailingDetailView),
        - при запуске рассылки (run_mailing).
        """
        qs = (
            super()
            .get_queryset()
            .select_related("message")
            .prefetch_related("clients")
            .annotate(clients_count=Count("clients", distinct=True))
        )

        for mailing in qs:
            mailing.update_status(save=False)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = self.object_list
        now = timezone.now()
        user = self.request.user

        cache_key = self._get_cache_key(user)

        stats = cache.get(cache_key)

        if stats is None:
            stats = {
                "total_mailings": qs.count(),
                "created_mailings": qs.filter(status="created").count(),
                "started_mailings": qs.filter(status="started").count(),
                "finished_mailings": qs.filter(status="finished").count(),
                "active_mailings": qs.filter(
                    status="started",
                    start_time__lte=now,
                    end_time__gte=now,
                ).count(),
            }
            cache.set(cache_key, stats, self.cache_timeout)

        context.update(stats)

        context["now"] = now
        return context

    @staticmethod
    def _get_cache_key(user) -> str:
        return f"mailings:summary:user:{user.pk}"


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("mailing:mailing_list")


class MailingUpdateView(LoginRequiredMixin, OwnerAccessMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = "mailing/mailing_form.html"

    def get_success_url(self):
        return reverse_lazy("mailing:mailing_detail", kwargs={"pk": self.object.pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class MailingDeleteView(LoginRequiredMixin, OwnerAccessMixin, DeleteView):
    model = Mailing
    template_name = "mailing/mailing_confirm_delete.html"
    success_url = reverse_lazy("mailing:mailing_list")


class MailingRunView(LoginRequiredMixin, View):

    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)

        if mailing.owner != request.user and not request.user.is_superuser:
            logger.warning(
                "Пользователь id=%s не имеет прав на запуск рассылки id=%s",
                request.user.id,
                mailing.id,
            )
            messages.error(request, "У вас нет прав на запуск этой рассылки.")
            return redirect("mailing:mailing_detail", pk=pk)

        logger.info(
            "Ручной запуск рассылки id=%s пользователем id=%s",
            mailing.id,
            request.user.id,
        )
        result = run_mailing(mailing)

        if not result["ok"]:
            logger.warning(
                "Ручной запуск рассылки невозможен: mailing_id=%s, user_id=%s, reason=%s",
                mailing.id,
                request.user.id,
                result.get("error", ""),
            )
            messages.error(request, result["error"])
        else:
            messages.success(
                request,
                (
                    f"Рассылка запущена. Всего клиентов: {result['total']}, "
                    f"успешно: {result['success']}, с ошибками: {result['failed']}."
                ),
            )

        return redirect("mailing:mailing_list")


class MailingDetailView(LoginRequiredMixin, OwnerQuerysetMixin, DetailView):
    model = Mailing
    template_name = "mailing/mailing_detail.html"
    context_object_name = "mailing"

    def get_object(self, queryset=None):
        obj = super().get_object()
        obj.update_status()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing = self.object
        now = timezone.now()

        interval_invalid = mailing.start_time >= mailing.end_time
        before_window = mailing.start_time > now
        after_window = mailing.end_time < now

        can_run = not interval_invalid and not before_window and not after_window and mailing.status != "finished"

        logs_qs = MailingLog.objects.filter(mailing=mailing).select_related("client").order_by("-attempt_time")

        stats = logs_qs.aggregate(
            total=Count("id"),
            success=Count("id", filter=Q(status="success")),
            failed=Count("id", filter=Q(status="failed")),
        )

        context["logs"] = logs_qs
        context["stats"] = stats
        context["interval_invalid"] = interval_invalid
        context["before_window"] = before_window
        context["after_window"] = after_window
        context["can_run"] = can_run
        context["now"] = now

        return context

mailing/templates/mailing/includes/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container">
    <small>© 2025 SkyMail | Учебный проект по Django (Skypro)</small>
  </div>
</footer>

mailing/templates/mailing/includes/_head.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}SkyMail — сервис рассылок{% endblock %}</title>

  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <style>
    :root {
      --skypro-blue: #007bff;
      --skypro-dark: #343a40;
    }

    body {
      font-family: 'Inter', sans-serif;
      background-color: #f8f9fa;
    }

    .card {
      border-radius: 1rem;
      box-shadow: 0 2px 6px rgba(0,0,0,0.1);
    }

    .navbar {
      background-color: var(--skypro-blue);
    }

    .navbar-brand {
      font-weight: 600;
      color: #fff !important;
    }

    .footer {
      background-color: var(--skypro-dark);
      color: #ccc;
    }
  </style>
</head>

mailing/templates/mailing/includes/_mailing_detail_panel.html
<!--mailing/_mailing_detail_panel.html-->

{# Предупреждение, если даты некорректны (для юзера/менеджера, если передали interval_invalid) #}
{% if interval_invalid %}
<div class="alert alert-danger mb-4">
    Интервал рассылки задан некорректно:
    дата окончания должна быть <strong>позже</strong> даты начала.<br>
    Текущие значения:<br>
    Начало: {{ mailing.start_time|date:"d.m.Y H:i" }}<br>
    Окончание: {{ mailing.end_time|date:"d.m.Y H:i" }}<br>
    Пожалуйста, отредактируйте рассылку перед запуском.
</div>
{% endif %}

{# Основная информация о рассылке #}
<div class="card border-0 shadow-sm mb-4">
    <div class="card-body">
        <h5 class="card-title mb-3">Информация о рассылке</h5>

        <dl class="row mb-0">
            <dt class="col-sm-3 col-md-4">Сообщение</dt>
            <dd class="col-sm-9 col-md-8">
                <strong>{{ mailing.message.subject|default:"(без темы)" }}</strong><br>
                <small class="text-muted">{{ mailing.message.body }}</small>
            </dd>

            <dt class="col-sm-3 col-md-4">Статус</dt>
            <dd class="col-sm-9 col-md-8">
                {% if mailing.status == "started" %}
                <span class="badge bg-success">{{ mailing.get_status_display }}</span>
                {% elif mailing.status == "finished" %}
                <span class="badge bg-secondary">{{ mailing.get_status_display }}</span>
                {% elif mailing.status == "created" %}
                <span class="badge bg-light text-dark">{{ mailing.get_status_display }}</span>
                {% else %}
                <span class="badge bg-light text-dark">Неизвестно</span>
                {% endif %}
            </dd>

            <dt class="col-sm-3 col-md-4">Дата начала</dt>
            <dd class="col-sm-9 col-md-8">
                {{ mailing.start_time|date:"d.m.Y H:i" }}
            </dd>

            <dt class="col-sm-3 col-md-4">Дата окончания</dt>
            <dd class="col-sm-9 col-md-8">
                {{ mailing.end_time|date:"d.m.Y H:i" }}
            </dd>

            <dt class="col-sm-3 col-md-4">Получателей</dt>
            <dd class="col-sm-9 col-md-8">
                {{ mailing.clients.count }}
            </dd>
        </dl>
    </div>
</div>

{# Краткая статистика по попыткам, если передана #}
{% if stats and stats.total %}
<p class="mb-3 small text-muted">
    Всего попыток: <strong>{{ stats.total }}</strong>,
    успешно: <strong class="text-success">{{ stats.success }}</strong>,
    с ошибкой: <strong class="text-danger">{{ stats.failed }}</strong>.
</p>
{% endif %}

{# Логи попыток отправки #}
{% if logs %}
<div class="card border-0 shadow-sm">
    <div class="card-body">
        <h5 class="card-title mb-3">Попытки рассылки</h5>

        <div class="table-responsive">
            <table class="table table-sm align-middle mb-0">
                <thead>
                <tr>
                    <th>Время</th>
                    <th>Получатель</th>
                    <th>Статус</th>
                    <th>Ответ сервера</th>
                </tr>
                </thead>
                <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{ log.attempt_time|date:"d.m.Y H:i:s" }}</td>
                    <td>
                        {% if log.client %}
                        {{ log.client.email }}
                        {% if log.client.full_name %}
                        <small class="text-muted">({{ log.client.full_name }})</small>
                        {% endif %}
                        {% else %}
                        <span class="text-muted">—</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if log.status == "success" %}
                        <span class="badge bg-success">{{ log.get_status_display }}</span>
                        {% else %}
                        <span class="badge bg-danger">{{ log.get_status_display }}</span>
                        {% endif %}
                    </td>
                    <td>{{ log.server_response }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
{% endif %}

mailing/templates/mailing/includes/_menu.html
<!--_menu.html-->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">SkyMail</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <!-- Основное меню -->
            {% if user.is_authenticated %}
            <ul class="navbar-nav me-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'mailing:message_list' %}">Сообщения</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mailing:client_list' %}">Получатели</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mailing:mailing_list' %}">Рассылки</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mailing:mailing_log' %}">Отчёты</a></li>
                {% if user.is_manager %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users:manager_dashboard' %}">Менеджер</a></li>
                {% endif %}

            </ul>

            <!-- Блок пользователя -->

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle d-flex align-items-center"
                       href="#"
                       id="userDropdown"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <!-- Аватар пользователя -->
                    <img
                            src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'img/default_avatar.png' %}{% endif %}"
                            alt="Аватар"
                            class="rounded-circle me-2"
                            width="32"
                            height="32"
                    >
                    <span>{{ request.user.email }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile_detail' %}">
                                Профиль
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form method="post" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <button class="dropdown-item" type="submit">
                                    Выйти
                                </button>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <div class="d-flex">
                <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2">Войти</a>
                <a href="{% url 'users:registration' %}" class="btn btn-primary">Регистрация</a>
            </div>
            {% endif %}
        </div>
    </div>
</nav>

mailing/templates/mailing/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="/">SkyMail</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="#">Сообщения</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Получатели</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Рассылки</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Отчёты</a></li>
            </ul>
        </div>
    </div>
</nav>